"use server";

import { z } from "zod";
import { MESSAGE_COLUMNS, MESSAGE_MAX, type MessageRow } from "@/lib/chat/types";
import { createClient } from "@/lib/db/server";
import { logServerError } from "@/lib/log";

const Input = z.object({
  conversationId: z.uuid(),
  // Generated by the client so the optimistic copy and the Realtime echo share one id.
  id: z.uuid(),
  body: z.string().trim().min(1).max(MESSAGE_MAX),
});

export type SendResult = { ok: true; message: MessageRow } | { ok: false };

/** Inserted as the signed-in user: RLS checks participation, a trigger sets sender_role. */
export async function sendMessage(input: z.input<typeof Input>): Promise<SendResult> {
  const parsed = Input.safeParse(input);
  if (!parsed.success) return { ok: false };
  const { conversationId, id, body } = parsed.data;

  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) return { ok: false };

  const { data, error } = await supabase
    .from("messages")
    // sender_role is required by the type but overwritten by the messages_before_insert trigger.
    .insert({ id, conversation_id: conversationId, sender_id: auth.user.id, sender_role: "asker", body })
    .select(MESSAGE_COLUMNS)
    .single();
  if (error) {
    logServerError("sendMessage", error, { conversationId });
    return { ok: false };
  }
  return { ok: true, message: data };
}
