import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire('/workspace/Wasl-audit-current-20261006/package.json');
const {createClient}=require('@supabase/supabase-js');
const {chromium}=require('playwright');
const BASE='http://127.0.0.1:3062', OUT='/workspace/wasl-release-audit-20261006/evidence/ui';
const creds=JSON.parse(readFileSync('/workspace/wasl-release-audit-20261006/local-state/credentials.json','utf8'));
assert.equal(creds.url,'http://127.0.0.1:55641');assert.equal(creds.prefix,'wasl-contextual-audit-20261006');
if(process.env.ANTHROPIC_API_KEY||process.env.ELEVENLABS_API_KEY) throw new Error('provider keys must be unset');
const db=createClient(creds.url,creds.service,{auth:{persistSession:false}});
const AR=JSON.parse(readFileSync('/workspace/Wasl-audit-current-20261006/messages/ar.json','utf8'));
const TAG=Date.now().toString(36), pseudonym=`UX${TAG}`;
const password=randomBytes(24).toString('base64url');
const fixtures={first:'أريد متابعة فكرة الدراسة، ناقشنا المقدمة لكنني لم أفهم التفاصيل.',reply:'يمكننا متابعة نقطة واحدة في اللقاء التالي.',selected:'ما زال ترتيب الخطوات غير واضح لي.',private:'مقطع اصطناعي حساس مستبعد من الاختيار.',followup:'أريد استئناف نقطة المتابعة التي اخترتها في بطاقتي.'};
const users=[],convs=[],results=[],images=[],requests=[],clientErrors=[];let orgId, browser, code;
function safe(value){let text=String(value);for(const v of [password,code,creds.anon,creds.service,...Object.values(fixtures)].filter(Boolean))text=text.split(v).join('[redacted]');return text.slice(0,700);}
function record(name,status,details={}){results.push({name,status,...details});console.log(`${status} ${name}`);}
async function query(name,promise){const result=await promise;if(result.error)throw new Error(`${name} failed(${result.error.code??'UNKNOWN'})`);return result.data;}
async function context(){const ctx=await browser.newContext({viewport:{width:1440,height:900}});await ctx.route('**/*',route=>{let url;try{url=new URL(route.request().url());}catch{return route.continue();}if(['http:','https:'].includes(url.protocol)&&!['127.0.0.1','localhost'].includes(url.hostname))return route.abort('blockedbyclient');return route.continue();});const page=await ctx.newPage();page.on('pageerror',e=>clientErrors.push({type:e.name,summary:safe(e.message)}));page.on('request',r=>{if(r.url().includes('/api/ai/'))requests.push({path:new URL(r.url()).pathname,method:r.method()});});return {ctx,page};}
async function shot(page,name){for(const [label,size]of Object.entries({desktop:{width:1440,height:900},mobile:{width:390,height:844}})){await page.setViewportSize(size);await page.waitForTimeout(150);const geometry=await page.evaluate(()=>({direction:document.documentElement.dir,overflow:document.documentElement.scrollWidth>innerWidth+1}));await page.evaluate(()=>{for(const el of document.querySelectorAll('.overflow-y-auto'))el.scrollTop=0;});const masks=page.locator('input:not([type=hidden]):not([type=checkbox]):not([type=radio]), textarea, [data-testid="return-code-value"], [dir="ltr"].select-all, [dir="auto"]:not(h1):not(h2), .whitespace-pre-wrap');const path=`${OUT}/${name}-${label}.png`;await page.screenshot({path,mask:[masks],maskColor:'#60698c',fullPage:false});images.push({name,label,path,...geometry,redaction:'inputs, return codes and dialogue/card bodies masked by Playwright'});}await page.setViewportSize({width:1440,height:900});}
async function enter(page){await page.goto(`${BASE}/ar/enter`);await page.locator('main input:not([type=hidden])').fill(pseudonym);await page.locator('main input:not([type=hidden])').press('Enter');await shot(page,'entry-background');await page.locator('button[name=skip]').click();await page.waitForURL('**/wait',{timeout:20000});}
async function login(page,email){await page.goto(`${BASE}/ar/login`);await page.locator('#login-email').fill(email);await page.locator('#login-password').fill(password);await page.locator('form button[type=submit]').click();await page.waitForURL('**/daee',{timeout:20000});}
async function say(page,selector,text){await page.locator(selector).fill(text);await page.locator(selector).press('Enter');}
async function next(page){await page.getByRole('button',{name:AR.Card.continue,exact:true}).click();}
async function phase(name,work){try{await work();}catch(e){record(name,'FAIL',{error:safe(e.message)});throw e;}}
try{
 browser=await chromium.launch({executablePath:'/usr/bin/chromium'});
 const visitors=await context();await visitors.page.goto(`${BASE}/ar`);await shot(visitors.page,'landing');record('public landing Arabic current render','PASS');
 const orgs=await query('check empty test organizations',db.from('organizations').select('id'));assert.equal(orgs.length,0,'default organization must be isolated and empty');
 const org=await query('create UX synthetic org',db.from('organizations').insert({name:'بيئة المراجعة الاصطناعية',ai_enabled:false,languages:['ar','en','fr','es','ur','id','tl']}).select('id').single());orgId=org.id;
 const staff=[];for(let i=0;i<2;i++){const email=`ux-${TAG}-${i}@example.invalid`;const response=await query('create UX synthetic staff',db.auth.admin.createUser({email,password,email_confirm:true}));users.push(response.user.id);await query('profile fixture',db.from('profiles').insert({user_id:response.user.id,org_id:orgId,role:'daee',display_name:i?'محاور اختبار ثانٍ':'محاور اختبار أول',languages:['ar'],topics:['general'],status:i?'busy':'available',last_seen:new Date().toISOString(),capacity:3}));const actor=await context();await login(actor.page,email);staff.push({...actor,id:response.user.id});}
 const asker=await context();await enter(asker.page);const ask=await query('find this UX asker',db.from('askers').select('user_id').eq('pseudonym',pseudonym).single());users.push(ask.user_id);
 await asker.page.locator('textarea[name=question]').waitFor();assert.equal(await asker.page.getByTestId('guide-unavailable').count(),1);await shot(asker.page,'manual-question-ai-off');
 await asker.page.locator('textarea[name=question]').fill(fixtures.first);await asker.page.locator('textarea[name=question]').press('Enter');await asker.page.waitForURL('**/chat/**',{timeout:20000});const conv=asker.page.url().split('/chat/')[1];convs.push(conv);record('entry → manual question → routing/wait (AI off)','PASS');
 const assignment=await query('read fixture assignment',db.from('conversations').select('daee_id,status').eq('id',conv).single());assert.equal(assignment.daee_id,staff[0].id);
 await staff[0].page.goto(`${BASE}/ar/daee/${conv}`);await staff[0].page.locator('main textarea').waitFor();await say(staff[0].page,'main textarea',fixtures.reply);await asker.page.getByText(fixtures.reply,{exact:true}).first().waitFor({timeout:15000});await say(asker.page,'footer textarea',fixtures.selected);await say(asker.page,'footer textarea',fixtures.private);await staff[0].page.getByText(fixtures.private,{exact:true}).first().waitFor({timeout:15000});await shot(asker.page,'human-chat');await shot(staff[0].page,'daee-chat');record('two-way local human chat and realtime','PASS');
 await asker.page.reload();await asker.page.getByText(fixtures.reply,{exact:true}).first().waitFor();record('refresh keeps own current conversation/messages','PASS');
 await asker.page.getByTestId('code-button').click();await asker.page.getByTestId('return-code-value').waitFor();code=(await asker.page.getByTestId('return-code-value').textContent()).trim();assert.match(code,/^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{2}$/);record('return code header first reveal (value not recorded)','PASS');await asker.page.keyboard.press('Escape');
 await asker.page.goto(`${BASE}/ar/card/${conv}`);const all=asker.page.locator('input[type=checkbox]');const preselected=await all.evaluateAll(nodes=>nodes.filter(n=>n.checked).length);record('card initial selection','OBSERVED',{checked:preselected,total:await all.count(),note:'all messages selected before an explicit checkbox action'});await shot(asker.page,'card-default-selection');
 await asker.page.getByRole('button',{name:AR.Card.selectNone,exact:true}).click();const messages=await query('fixture message IDs',db.from('messages').select('id,body').eq('conversation_id',conv).order('created_at'));await asker.page.locator('ul li label').nth(0).click();await asker.page.locator('ul li label').nth(2).click();await next(asker.page);await asker.page.locator('#card-follow_up').fill('نقطة متابعة اصطناعية');await asker.page.locator('#card-covered').fill('تناولنا المقدمة؛ لم يتأكد الفهم.');await asker.page.locator('#card-next_step').fill('موعد متابعة اصطناعي');await shot(asker.page,'card-manual-editor');await next(asker.page);await asker.page.locator('label',{hasText:AR.Card.team}).click();await shot(asker.page,'card-sharing');await next(asker.page);await shot(asker.page,'card-review');
 const before=await query('fixture cards before approval',db.from('cards').select('id,status').eq('conversation_id',conv));assert.equal(before.length,0);await asker.page.getByRole('button',{name:AR.Card.approve,exact:true}).click();await asker.page.getByRole('button',{name:AR.Card.newVersion,exact:true}).waitFor({timeout:20000});const card=await query('approved fixture card',db.from('cards').select('id,status,version,source_message_ids,field_sources').eq('conversation_id',conv).single());assert.equal(card.status,'approved');assert.equal(card.source_message_ids.length,2);assert.equal(card.source_message_ids.includes(messages.find(m=>m.body===fixtures.private).id),false);await shot(asker.page,'card-approved');record('selected manual card → direct asker approval without human review','PASS',{selectedCount:2,status:'approved',humanReviewPerformed:false});
 await staff[0].page.reload();await staff[0].page.getByText('نقطة متابعة اصطناعية',{exact:true}).waitFor();record('current human receives approved card','PASS');
 await query('make transfer fixture available',db.from('profiles').update({status:'available',last_seen:new Date().toISOString()}).eq('user_id',staff[1].id));await staff[0].page.locator('main header').getByRole('button',{name:AR.Inbox.transfer,exact:true}).click();await staff[0].page.getByRole('radio',{name:/محاور اختبار ثان/}).click();await shot(staff[0].page,'transfer-menu');await staff[0].page.getByRole('dialog').getByRole('button',{name:AR.Inbox.confirmTransfer,exact:true}).click();await staff[0].page.waitForURL(/\/daee$/,{timeout:20000});await staff[1].page.goto(`${BASE}/ar/daee/${conv}`);await staff[1].page.getByText('نقطة متابعة اصطناعية',{exact:true}).waitFor();const archiveVisible=await staff[1].page.getByText(fixtures.private,{exact:true}).first().isVisible();await shot(staff[1].page,'transferred-daee');const after=await query('after transfer fixture state',db.from('conversations').select('id,daee_id').eq('id',conv).single());assert.equal(after.daee_id,staff[1].id);record('transfer to second human','PASS',{sameConversationId:true,previousUnselectedMessageVisibleToNext:archiveVisible});
 await staff[1].page.getByRole('button',{name:AR.Inbox.end??/إنهاء/}).first().click();await staff[1].page.getByRole('button',{name:AR.Inbox.confirmEnd,exact:true}).click();await asker.page.goto(`${BASE}/ar/chat/${conv}`);await asker.page.getByTestId('return-code-value').waitFor({timeout:20000});const endedCode=(await asker.page.getByTestId('return-code-value').textContent()).trim();const rotates=endedCode!==code;code=endedCode;await shot(asker.page,'ended-return-code-masked');record('human end → return code revealed','PASS',{rotatedFromHeaderCode:rotates});
 const returning=await context();await returning.page.goto(`${BASE}/ar/return`);await returning.page.locator('#return-pseudonym').fill(pseudonym);await returning.page.locator('#return-code').fill(code);await returning.page.locator('main form button[type=submit]').click();await returning.page.waitForURL('**/wait',{timeout:20000});await shot(returning.page,'return-resume-choice');await returning.page.getByRole('button',{name:/تابع مع/}).click();await returning.page.locator('textarea[name=question]').fill(fixtures.followup);await returning.page.locator('textarea[name=question]').press('Enter');await returning.page.waitForURL('**/chat/**',{timeout:20000});const resumed=returning.page.url().split('/chat/')[1];convs.push(resumed);const res=await query('resumed link',db.from('conversations').select('previous_conversation_id,card_id,daee_id,followup_mode').eq('id',resumed).single());assert.equal(res.previous_conversation_id,conv);assert.equal(res.card_id,card.id);await shot(returning.page,'resumed-chat');record('new-browser return → preferred human choice → linked new session','PASS',{cardLinked:true,previousLinked:true,mode:res.followup_mode,sameHumanAsCard:res.daee_id===staff[0].id});
 // Bounded failure check on a fresh manual editor: offline request does not erase typed fields.
 await returning.page.goto(`${BASE}/ar/card/${resumed}`);await next(returning.page);await returning.page.locator('#card-follow_up').fill('مسودة اصطناعية لاختبار الانقطاع');await returning.ctx.setOffline(true);await next(returning.page);await next(returning.page);await returning.page.getByRole('button',{name:AR.Card.saveDraft,exact:true}).click();await returning.page.waitForTimeout(1500);await returning.page.getByRole('button',{name:AR.Card.back,exact:true}).click();await returning.page.getByRole('button',{name:AR.Card.back,exact:true}).click();const retained=await returning.page.locator('#card-follow_up').inputValue()==='مسودة اصطناعية لاختبار الانقطاع';await returning.ctx.setOffline(false);record('offline draft save retains local editor text','OBSERVED',{retained});
 // Guide is enabled in LOCAL org only; provider keys remain empty so no paid request.
 await query('enable local guide for missing-key fallback',db.from('organizations').update({ai_enabled:true}).eq('id',orgId));const guide=await context();await guide.page.goto(`${BASE}/ar/enter`);await guide.page.locator('main input:not([type=hidden])').fill(`UG${TAG}`);await guide.page.locator('main input:not([type=hidden])').press('Enter');await guide.page.locator('button[name=skip]').click();await guide.page.waitForURL('**/wait');await guide.page.getByTestId('guide').waitFor();await shot(guide.page,'guide-initial');const mic=guide.page.getByRole('button',{name:AR.Guide.speak,exact:true});const micPresent=await mic.count();if(micPresent){await mic.click();await guide.page.waitForTimeout(1000);record('microphone attempted with browser permission unset','OBSERVED',{micPresent,stillVisible:await mic.count()});}else record('microphone control capability','UNVERIFIED',{reason:'browser exposes no recognition control'});await guide.page.getByTestId('guide-skip').click();await guide.page.locator('textarea[name=question]').waitFor();await shot(guide.page,'guide-manual-skip');record('guide skip reaches manual question composer','PASS');
}catch(e){process.exitCode=1;record('bounded browser journey stopped','FAIL',{error:safe(e.message)});if(browser)for(const [i,c]of browser.contexts().entries())for(const [j,p]of c.pages().entries())await shot(p,`failure-${i}-${j}`).catch(()=>{});
}finally{
 if(browser)await browser.close();try{if(orgId){const owned=await query('find owned UX identities',db.from('askers').select('user_id').eq('org_id',orgId));users.push(...owned.map(a=>a.user_id));await query('cleanup UX events',db.from('events').delete().eq('org_id',orgId));await query('cleanup UX AI runs',db.from('ai_runs').delete().eq('org_id',orgId));for(const id of [...new Set(users)].reverse()){await query('cleanup UX notifications',db.from('notifications').delete().eq('recipient_id',id));await query('cleanup UX auth user',db.auth.admin.deleteUser(id));}await query('cleanup UX org',db.from('organizations').delete().eq('id',orgId));record('cleanup of owned synthetic local fixtures','PASS');}}catch(e){record('cleanup of owned synthetic fixtures','FAIL',{error:safe(e.message)});}const report={sha:'675a2e0089ee1e4324a7b438c17d570989793bc1',runtime:{app:BASE,api:creds.url,kind:'real local Auth/REST/Realtime, PostgreSQL17, current migrations0001–0018'},providerKeys:'unset; no paid calls',fixtureNamespace:'UX audit synthetic identities only',results,images,requests,clientErrors:clientErrors.map(e=>({type:e.type,summary:safe(e.summary)}))};writeFileSync(`${OUT}/results.json`,JSON.stringify(report,null,2));console.log('Saved privacy-masked current screenshots and results.json');}
