import assert from 'node:assert/strict';
import { AuditUsageGuard,ALLOWED_MODEL } from './usage-guard.mjs';
const url='https://api.anthropic.com/v1/messages';
const request={ method:'POST',body:JSON.stringify({model:ALLOWED_MODEL,max_tokens:64000,messages:[{role:'user',content:'synthetic'}]}) };
const message=()=>new Response(JSON.stringify({type:'message',model:ALLOWED_MODEL,usage:{input_tokens:100,output_tokens:20,cache_creation_input_tokens:0,cache_read_input_tokens:0}}),{headers:{'content-type':'application/json'}});
let active=0,maxActive=0,calls=0;
const g=new AuditUsageGuard({fetchImpl:async()=>{calls++;active++;maxActive=Math.max(maxActive,active);await new Promise(r=>setTimeout(r,5));active--;return message();}});
await Promise.all([g.fetch(url,request),g.fetch(url,request)]);await g.wait();
assert.equal(calls,2);assert.equal(maxActive,1);assert.ok(g.committedUsd<.001);assert.ok(g.records.every(r=>r.usage_complete));
let invoked=0;
const unknown=new AuditUsageGuard({fetchImpl:async()=>{invoked++;return new Response(JSON.stringify({type:'message',model:ALLOWED_MODEL,usage:{input_tokens:10,output_tokens:1}}),{headers:{'content-type':'application/json'}});}});
await unknown.fetch(url,request);await unknown.wait();assert.equal(unknown.committedUsd,.72);assert.equal(unknown.records[0].usage.cache_read_input_tokens,null);
await assert.rejects(()=>unknown.fetch(url,request),/stopped/);assert.equal(invoked,1);
const blocked=new AuditUsageGuard({fetchImpl:async()=>{throw new Error('must_not_fetch');}});
await assert.rejects(()=>blocked.fetch(url,{...request,body:JSON.stringify({model:ALLOWED_MODEL,max_tokens:1024,tools:[{type:'web_search_20250305'}]})}),/opaque_tools/);
assert.equal(blocked.records.length,0);
await assert.rejects(()=>blocked.fetch(url,{...request,body:JSON.stringify({model:'unsupported',max_tokens:1})}),/unsupported_model/);
const budget=new AuditUsageGuard({fetchImpl:async()=>message()});budget.committedUsd=.400005;
await assert.rejects(()=>budget.fetch(url,request),/global_budget/);assert.equal(budget.records.length,0);
console.log('PASS audit guard: serialized fetch, complete-usage reconciliation, null retention, unknown fail-closed, no native tools, unsupported model, immutable global $1 cap');
let transportTokens=null;
const bounded=new AuditUsageGuard({outputTokensCap:1024,fetchImpl:async(u,i)=>{transportTokens=JSON.parse(i.body).max_tokens;return message();}});
bounded.committedUsd=.400005;
await bounded.fetch(url,request);await bounded.wait();
assert.equal(transportTokens,1024);assert.equal(bounded.records[0].original_requested_max_tokens,64000);assert.equal(bounded.records[0].effective_max_tokens,1024);assert.ok(Math.abs(bounded.records[0].reservation_usd-.40512)<1e-12);assert.ok(bounded.committedUsd>.400005&&bounded.committedUsd<1);
console.log('PASS approved bounded transport variant: original64K recorded, effective1024, old unknown reservation preserved');
