#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
# No environment file is loaded and no paid provider is used by these checks.
env -u ANTHROPIC_API_KEY -u ELEVENLABS_API_KEY WASL_RECOMMENDATIONS_PAID_APPROVED=false WASL_RECOMMENDATIONS_FREE_FETCH=false \
  node --import tsx --conditions=react-server --test tests/recommendations/*.test.ts
node --test tests/recommendations/provider-sdk.test.mjs
# PageProps/LayoutProps are generated by Next; a fresh checkout has no .next/types.
# typegen builds route types only. It never runs a migration or provider request.
env -u ANTHROPIC_API_KEY -u ELEVENLABS_API_KEY WASL_RECOMMENDATIONS_PAID_APPROVED=false npx next typegen
npx tsc --noEmit --incremental false
npm run lint
